import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import cv2
import glob
import os
from datetime import datetime
from PIL import Image
import numpy as np

st.set_page_config(page_title="AI Proctoring System", page_icon="🎓", layout="wide")

st.markdown("""
<style>
    .main-header {
        background: linear-gradient(90deg, #1a1a2e, #16213e);
        padding: 20px;
        border-radius: 10px;
        text-align: center;
        color: white;
        margin-bottom: 20px;
    }
    .metric-card {
        background: #f0f2f6;
        padding: 15px;
        border-radius: 10px;
        text-align: center;
    }
    .high-risk { color: #dc3545; font-weight: bold; }
    .medium-risk { color: #fd7e14; font-weight: bold; }
    .low-risk { color: #28a745; font-weight: bold; }
</style>
""", unsafe_allow_html=True)

st.markdown("""
<div class="main-header">
    <h1>🎓 AI Proctoring System</h1>
    <p>Explainable AI-powered exam monitoring</p>
</div>
""", unsafe_allow_html=True)

st.sidebar.title("Navigation")
page = st.sidebar.radio("Go to", ["📊 Session Reports", "ℹ️ About"])

def load_session_data(csv_path):
    df = pd.read_csv(csv_path)
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    return df

def get_risk_level(score):
    if score < 10:
        return "LOW", "low-risk"
    elif score < 25:
        return "MEDIUM", "medium-risk"
    else:
        return "HIGH", "high-risk"

def plot_event_bar_chart(df):
    event_colors = {
        "LOOKING_AWAY": "#FFA500",
        "MULTIPLE_FACES": "#FF4500",
        "NO_FACE": "#DC143C",
        "PHONE_DETECTED": "#8B0000",
        "LAPTOP_DETECTED": "#800080",
        "BOOK_DETECTED": "#4169E1",
    }
    event_counts = df['event_type'].value_counts()
    colors = [event_colors.get(e, "#888888") for e in event_counts.index]
    fig, ax = plt.subplots(figsize=(10, 4))
    bars = ax.bar(event_counts.index, event_counts.values, color=colors)
    for bar, count in zip(bars, event_counts.values):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.1, str(count), ha='center', va='bottom', fontweight='bold')
    ax.set_title("Event Frequency", fontsize=13, fontweight='bold')
    ax.set_xlabel("Event Type")
    ax.set_ylabel("Count")
    ax.tick_params(axis='x', rotation=30)
    plt.tight_layout()
    return fig

def plot_timeline(df):
    event_colors = {
        "LOOKING_AWAY": "#FFA500",
        "MULTIPLE_FACES": "#FF4500",
        "NO_FACE": "#DC143C",
        "PHONE_DETECTED": "#8B0000",
        "LAPTOP_DETECTED": "#800080",
        "BOOK_DETECTED": "#4169E1",
    }
    session_start = df['timestamp'].min()
    df['minutes_elapsed'] = (df['timestamp'] - session_start).dt.total_seconds() / 60
    event_types = df['event_type'].unique()
    fig, ax = plt.subplots(figsize=(12, 4))
    for i, event_type in enumerate(event_types):
        events = df[df['event_type'] == event_type]
        color = event_colors.get(event_type, "#888888")
        ax.scatter(events['minutes_elapsed'], [i] * len(events), c=color, s=80, zorder=3)
        ax.axhline(y=i, color='gray', linestyle='--', alpha=0.3)
    ax.set_yticks(range(len(event_types)))
    ax.set_yticklabels(event_types, fontsize=9)
    ax.set_xlabel("Time into Exam (minutes)")
    ax.set_title("Event Timeline", fontsize=13, fontweight='bold')
    ax.grid(axis='x', alpha=0.3)
    plt.tight_layout()
    return fig

def plot_score_over_time(df):
    session_start = df['timestamp'].min()
    df['minutes_elapsed'] = (df['timestamp'] - session_start).dt.total_seconds() / 60
    fig, ax = plt.subplots(figsize=(12, 3))
    ax.plot(df['minutes_elapsed'], df['cumulative_score'], color='#dc3545', linewidth=2, marker='o', markersize=4)
    ax.fill_between(df['minutes_elapsed'], df['cumulative_score'], alpha=0.2, color='#dc3545')
    ax.set_xlabel("Time into Exam (minutes)")
    ax.set_ylabel("Suspicion Score")
    ax.set_title("Suspicion Score Over Time", fontsize=13, fontweight='bold')
    ax.grid(alpha=0.3)
    plt.tight_layout()
    return fig

if page == "📊 Session Reports":
    st.header("Session Reports")
    st.markdown("---")
    st.subheader("📁 Upload a Session Report")
    
    st.markdown("Don't have a file? Download a sample to test the dashboard:")
    try:
        with open("sample_session.csv", "rb") as f:
            st.download_button("📄 Download Sample CSV", f, file_name="sample_session.csv", mime="text/csv")
    except FileNotFoundError:
        st.error("Sample file not found on server.")

    st.markdown("Test the dashboard by uploading a `session_log.csv` file generated by the AI Proctor.")
    uploaded_file = st.file_uploader("Drag and drop your CSV file here", type=["csv"])
    st.markdown("---")

    df = None
    session_name = "Uploaded_Session"
    is_uploaded_file = False

    if uploaded_file is not None:
        df = load_session_data(uploaded_file)
        session_name = uploaded_file.name.replace(".csv", "")
        is_uploaded_file = True
        st.success("File uploaded successfully! Generating live report...")
    else:
        csv_files = glob.glob("logs/session_*.csv")
        if not csv_files:
            st.info("No local session logs found. Please upload a CSV file above to view the dashboard.")
        else:
            csv_files = sorted(csv_files, key=os.path.getmtime, reverse=True)
            session_names = [os.path.basename(f).replace("session_", "").replace(".csv", "") for f in csv_files]
            selected_session = st.selectbox("Select Local Session to View", session_names, index=0)
            selected_csv = f"logs/session_{selected_session}.csv"
            df = load_session_data(selected_csv)
            session_name = selected_session

    if df is not None:
        total_score = df['cumulative_score'].max()
        total_events = len(df)
        session_start = df['timestamp'].min()
        session_end = df['timestamp'].max()
        duration = (session_end - session_start).total_seconds() / 60
        risk_level, risk_class = get_risk_level(total_score)

        col1, col2, col3, col4 = st.columns(4)
        with col1:
            st.metric("Total Events", total_events)
        with col2:
            st.metric("Suspicion Score", total_score)
        with col3:
            st.metric("Duration", f"{duration:.1f} min")
        with col4:
            st.metric("Risk Level", risk_level)

        st.markdown(f"### Risk Assessment: <span class='{risk_class}'>{risk_level}</span>", unsafe_allow_html=True)
        st.subheader("Suspicion Score Progression")
        st.pyplot(plot_score_over_time(df))

        col1, col2 = st.columns(2)
        with col1:
            st.subheader("Event Frequency")
            st.pyplot(plot_event_bar_chart(df))
        with col2:
            st.subheader("Event Timeline")
            st.pyplot(plot_timeline(df))

        st.subheader("Event Breakdown")
        event_summary = df.groupby('event_type').agg(
            Count=('event_type', 'count'),
            Severity=('severity', 'first'),
            Total_Score_Impact=('severity', 'sum')
        ).reset_index()
        event_summary.columns = ['Event Type', 'Count', 'Severity Per Event', 'Total Score Impact']
        st.dataframe(event_summary, use_container_width=True)

        st.subheader("Full Event Log")
        st.dataframe(df[['timestamp', 'event_type', 'severity', 'details', 'cumulative_score']], use_container_width=True)

        if not is_uploaded_file:
            st.markdown("---")
            pdf_path = f"reports/report_{session_name}.pdf"
            if os.path.exists(pdf_path):
                with open(pdf_path, "rb") as f:
                    st.download_button(
                        label="📥 Download PDF Report",
                        data=f,
                        file_name=f"report_{session_name}.pdf",
                        mime="application/pdf"
                    )
            else:
                if st.button("Generate PDF Report"):
                    from report_generator import generate_pdf_report
                    with st.spinner("Generating report..."):
                        generate_pdf_report(selected_csv, "Student")
                    st.success("Report generated!")
                    st.rerun()

elif page == "ℹ️ About":
    st.header("About This System")
    st.markdown("""
    ## AI Proctoring System
    
    An explainable AI-powered exam monitoring system built with:
    
    ### Technology Stack
    - **Python** — Core programming language
    - **OpenCV** — Real time video processing
    - **MediaPipe** — Face mesh and iris landmark detection (468 points)
    - **YOLOv8** — Object detection for phones and unauthorized materials
    - **Pandas** — Data logging and analysis
    - **Matplotlib** — Behavioral charts and visualizations
    - **FPDF** — Automated PDF report generation
    - **Streamlit** — Interactive web dashboard
    
    ### Detection Capabilities
    - **Gaze Tracking** — Head pose + iris position dual layer detection
    - **Multiple Face Detection** — Identifies unauthorized persons in frame
    - **Object Detection** — Phones, laptops, books
    - **No Face Detection** — Student leaving the frame
    
    ### What Makes This Different
    Unlike commercial proctoring systems that are black boxes,
    this system provides full explainability — every flag includes
    exactly what was detected, when, and why it was considered suspicious.
    
    ### Ethical Considerations
    - Eye closure removed as a metric (thinking is not cheating)
    - Conservative thresholds to minimize false positives
    - Transparent scoring with severity weights
    - Full audit trail for every decision
    """)